# Generated by Django 6.0.5 on 2026-05-28 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeConservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Unidade')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('localizacao', models.CharField(max_length=250, verbose_name='Localização')),
                ('imagem_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Imagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_remetente', models.CharField(max_length=150, verbose_name='Seu Nome')),
                ('email_remetente', models.EmailField(max_length=254, verbose_name='Seu Email')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicacoes', to='unidades.unidadeconservacao')),
            ],
        ),
    ]
