# Generated by Django 6.0.5 on 2026-05-28 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Instituição')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Município')),
            ],
        ),
        migrations.RemoveField(
            model_name='comunicacao',
            name='email_remetente',
        ),
        migrations.RemoveField(
            model_name='comunicacao',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='comunicacao',
            name='nome_remetente',
        ),
        migrations.RemoveField(
            model_name='unidadeconservacao',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='comunicacao',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comunicacao',
            name='email',
            field=models.CharField(default=1, max_length=150, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comunicacao',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Pendente'), (2, 'Em Andamento'), (3, 'Resolvido')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='comunicacao',
            name='titulo',
            field=models.CharField(default='', max_length=200, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='unidadeconservacao',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='unidadeconservacao',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='unidadeconservacao',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL da Imagem'),
        ),
        migrations.AddField(
            model_name='unidadeconservacao',
            name='instituicao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='unidades.instituicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidadeconservacao',
            name='municipios',
            field=models.ManyToManyField(related_name='unidades', to='unidades.municipio'),
        ),
    ]
