# Generated by Django 6.0.5 on 2026-05-28 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_instituicao_municipio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicacao',
            options={'verbose_name': 'Comunicação', 'verbose_name_plural': 'Comunicações'},
        ),
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
        migrations.AlterModelOptions(
            name='unidadeconservacao',
            options={'verbose_name': 'Unidade de Conservação', 'verbose_name_plural': 'Unidades de Conservação'},
        ),
    ]
