# Generated by Django 6.0.5 on 2026-05-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0004_unidadeconservacao_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadeconservacao',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='unidadeconservacao',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='unidades/', verbose_name='Imagem'),
        ),
    ]
