# Generated by Django 6.0.5 on 2026-05-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0005_remove_unidadeconservacao_imagem_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicacao',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Comunicação', 'verbose_name_plural': 'Comunicações'},
        ),
        migrations.AlterField(
            model_name='comunicacao',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Em análise'), (1, 'Analisada')], default=0, verbose_name='Status'),
        ),
    ]
