# Generated by Django 6.0.5 on 2026-05-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0006_alter_comunicacao_options_alter_comunicacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeconservacao',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área (hectares)'),
        ),
        migrations.AlterField(
            model_name='unidadeconservacao',
            name='data_criacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
